[package]
name = "madevent"
version = "0.1.2"
publish = true
edition = "2021"
license = "AGPL-3.0"
description = "Client for madevent"
repository = "https://github.com/timayz/madevent"
homepage = "https://madevent.timada.co"

[dependencies]
serde = { version = "1.0.215", features = ["derive"] }
futures = "0.3.31"
ulid = { version = "1.1.3", features = ["serde"] }

[dev-dependencies]
tokio = "1.41.1"

